WebOficios/Models/Pager.cs
namespace WebOficios.Models
{
    public class Pager
    {
        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }

        public int PageSize { get; private set; }

        public int TotalPages { get; private set; }

        public int StartPage { get; private set; }

        public int EndPage { get; private set; }

        public Pager()
        {

        }

        public Pager(int totalItems, int page, int pageSize = 10)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage=page;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if(StartPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }

            if(endPage>totalPages)
            {
                endPage = totalPages;
                if(endPage > 10)
                {
                    startPage = endPage - 9;

                }  
            }
            TotalPages = totalPages;
            CurrentPage = currentPage;
            TotalItems = totalItems;
            StartPage = startPage;
            EndPage = endPage;
            PageSize=pageSize;
        }
    }
}

WebOficios/Controllers/DireccionesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebOficios.Data;
using WebOficios.Models;

namespace WebOficios.Controllers
{
    public class DireccionesController : Controller
    {

        private readonly oficiosContext _context;

        public DireccionesController(oficiosContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index(int pg = 1)
        {
            
            const int pageSize = 10;

            if(pg < 1)
            {
                pg = 1;
            }

            int recsCount = _context.Direcciones.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;

            List<Direccion> direcciones = _context.Direcciones.Skip(recSkip).Take(pager.PageSize).ToList();

            var totalRegistros = (from d in _context.Direcciones select d).Count();
            this.ViewBag.TotalRegistros = totalRegistros;   
            this.ViewBag.Pager = pager;
            return View(direcciones);
        }
      
        [Authorize]
        public async Task<IActionResult> Create(int? id)
        {
            Direccion direccion = new Direccion();
            
            if (id == null) 
            { 
                return View(direccion);
            }
            else
            {
                direccion = await _context.Direcciones.FindAsync(id);
                return View(direccion);
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Direccion direccion)
        {

            if (ModelState.IsValid)
            {
                if(direccion.IdDireccion == 0) //Crear registro
                { 
                    await _context.Direcciones.AddAsync(direccion);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create), new { id = 0 }); //Lo añadí para que al momento de añadir uno nuevo no salte el modal del último registro
                }
                else
                {
                    _context.Direcciones.Update(direccion);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create), new { id=0 });
                }
            }

            return View(direccion);
        }

        [HttpGet]
        public async Task<IActionResult> Listado()
        {
            var lst = await _context.Direcciones.ToListAsync();
            return Json(new {data = lst});
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {

            var direccion = await _context.Direcciones.FindAsync(id);
            if (direccion == null)
            {
                return Json(new { success = false, message = "No se pudo borrar el registro" });
            }

            _context.Direcciones.Remove(direccion);
            await _context.SaveChangesAsync();
            return Json(new { success = true, message = "Dirección borrada con éxito" });

        }
    }
}

WebOficios/Controllers/OficiosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebOficios.Data;
using WebOficios.Models;



namespace WebOficios.Controllers
{
    public class OficiosController : Controller
    {
        private readonly oficiosContext _context;
        private readonly IWebHostEnvironment _enviroment;

        public OficiosController(oficiosContext context, IWebHostEnvironment env)
        {
            _context = context;
            _enviroment = env;  
        }

        [ValidateAntiForgeryToken]
        [Authorize]
        // GET: OficiosController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Listado(int id)
        {
            var lst = (from Oficios in _context.Oficios
                       join TipoOficios in _context.TipoOficios on Oficios.IdTipo equals TipoOficios.IdTipo
                       join Direcciones in _context.Direcciones on Oficios.IdDireccion equals Direcciones.IdDireccion
                       select new
                       {
                           idOficio = Oficios.IdOficio,
                           numOficio = Oficios.NOficio,
                           fecha = Oficios.Fecha,
                           tipoOficio = TipoOficios.Nombre,
                           asunto = Oficios.Asunto,
                           nombreDireccion = Direcciones.Nombre,
                           folioSolicitud = Oficios.FolioSolicitud,
                           usuario=Oficios.Capturo


                       }).ToList();

            return  Json (new  {  data = lst });
        }

        [Authorize]
        [HttpGet]
        // GET: OficiosController/Create
        public async Task<ActionResult> Create(int? id)
        {
            Oficio Oficio = new();
            ViewBag.Tipos = _context.TipoOficios.Select(t => new { IdTipo = t.IdTipo, Nombre = t.Nombre}).ToList();

            ViewBag.Direcciones = _context.Direcciones.Select(d => new { IdDireccion = d.IdDireccion, Nombre = d.Nombre}).ToList();

            

            if (id == null)
            {

                return View(Oficio);
            }
            else
            {
                
                Oficio = await _context.Oficios.FindAsync(Convert.ToInt64(id));
                return View(Oficio);
            }
        }

        // POST: OficiosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Oficio oficio )
        {

            

            ViewBag.Tipos = _context.TipoOficios.Select(t => new { IdTipo = t.IdTipo, Nombre = t.Nombre }).ToList();

            ViewBag.Direcciones = _context.Direcciones.Select(d => new { IdDireccion = d.IdDireccion, Nombre = d.Nombre }).ToList();

           
            if (ModelState.IsValid)
            {
                

                if (oficio.IdOficio == 0) //Crear registro
                {
                   

                        using (var ms = new MemoryStream())
                        {
                            await oficio.FormFile.CopyToAsync(ms);


                            oficio.PdfArchivo = ms.ToArray();
                            
                                
                        };
                    

                    await _context.Oficios.AddAsync(oficio);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create), new { id = 0 }); //Lo añadí para que al momento de añadir uno nuevo no salte el modal del último registro
                }
                else
                {
                    using (var ms = new MemoryStream())
                    {
                        await oficio.FormFile.CopyToAsync(ms);


                        oficio.PdfArchivo = ms.ToArray();


                    };


                    _context.Oficios.Update(oficio);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create), new { id = 0 });
                }
            }
           

            return View(oficio);
        }



        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            var oficio = await _context.Oficios.FindAsync(Convert.ToInt64(id));
            if (oficio == null)
            {
                return Json(new { success = false, message = "No se pudo borrar el registro" });
            }

            _context.Oficios.Remove(oficio);
            await _context.SaveChangesAsync();
            return Json(new { success = true, message = "Oficio borrado con éxito" });
        }

      [Route("~/OnPostDownLoadAsync/{id}")]
        public async Task<ActionResult> OnPostDownLoadAsync(int id)
        {

            using (var db = new oficiosContext()) 
            { 
                var miOficio = await db.Oficios.FindAsync(Convert.ToInt64(id));
                return File(miOficio.PdfArchivo, "application/pdf", fileDownloadName: $"Oficio número {miOficio.NOficio}.pdf");
            }
            
        }


    }
}

WebOficios/Controllers/TipoOficiosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebOficios.Data;
using WebOficios.Models;

namespace WebOficios.Controllers
{
    public class TipoOficiosController : Controller
    {

        private readonly oficiosContext _context;

        public TipoOficiosController(oficiosContext context)
        {
            _context = context;
        }
       
        public IActionResult Index()
        {
            return View();
        }


        [Authorize]
        public async Task<IActionResult> Create(int? id )
        {
            TipoOficio tOficio = new TipoOficio();
            
            if (id == null)
            {
                return View(tOficio);
            }
            else
            {
                tOficio = await _context.TipoOficios.FindAsync(id);
                return View(tOficio);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TipoOficio tOficio)
        {

            if (ModelState.IsValid)
            {
                if (tOficio.IdTipo == 0) //Crear registro
                {
                    await _context.TipoOficios.AddAsync(tOficio);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create), new { id = 0 }); //Lo añadí para que al momento de añadir uno nuevo no salte el modal del último registro
                }
                else
                {
                    _context.TipoOficios.Update(tOficio);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create), new { id = 0 });
                }
            }

            return View(tOficio);
        }

        [HttpGet]
        public async Task<IActionResult> Listado()
        {
            var lst = await _context.TipoOficios.ToListAsync();
            return Json(new { data = lst });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {

            var tOficio = await _context.TipoOficios.FindAsync(id);
            if (tOficio == null)
            {
                return Json(new { success = false, message = "No se pudo borrar el registro" });
            }

            _context.TipoOficios.Remove(tOficio);
            await _context.SaveChangesAsync();
            return Json(new { success = true, message = "Registro borrado con éxito" });

        }


    }
}

WebOficios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Control de Oficios - Unidad de Transparencia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css"/>


    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>  
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebOficios.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
 
</head>
<body>
    <header>
        <div class="contenedor">
    <div class="barra-layout">
       <nav class="navegacion">
                <a class="navegacion__enlace color-enlaces portal" asp-area="" asp-controller="Home" asp-action="Index">Portal<span class="oficio">Oficios</span></a>
                
                    
                        @if (User.Identity.IsAuthenticated)
                        {
                            
                                <a class="navegacion__enlace color-enlaces" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            
                        
                          
                                <a class="navegacion__enlace color-enlaces" asp-area="" asp-controller="Oficios" asp-action="Create">Oficios</a>
                            
                        
                            
                                <a class="navegacion__enlace  color-enlaces" asp-area="" asp-controller="Direcciones" asp-action="Create">Direcciones</a>
                            
                            
                                <a class="navegacion__enlace color-enlaces" asp-area="" asp-controller="TipoOficios" asp-action="Create">Tipos de Oficios</a>
                            
                        } 

                        
                   
                    <partial name="_LoginPartial" />
               
        </nav>
        </div>
         </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="bottom:auto;">
        <div class="container">
            &copy; By L.I.A Luis Jorge Carrillo Quiroz 2022 - Control de Oficios @*- <a class="link-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Política de privacidad</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebOficios/Views/Shared/_Pager.cshtml
@model WebOficios.Models.Pager

<div class="container">
	@if (Model.TotalPages > 0)
	{
		<ul class="pagination justify-content-end">

			@if(Model.CurrentPage > 1)
			{
				<li class=" page-item">
					<a class="page-link" asp-controller="Direcciones" asp-action="Index" asp-route-pg="1">Primero</a>
				</li>

				<li>
					<a class="page-link" asp-controller="Direcciones" asp-action="Index"
						asp-route-pg="@Model.CurrentPage - 1)">Anterior</a>
				</li>
			}

			@for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
			{
				<li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
					<a class="page-link" asp-controller="Direcciones" asp-action="Index" 
						asp-route-pg="@pge"> @pge </a>
				</li>
			}

			@if (Model.CurrentPage < Model.TotalPages)
			{
				<li class="page-item">
					<a class="page-link" asp-controller="Direcciones" asp-action="Index"
						asp-route-pg="@(Model.CurrentPage + 1)">Siguiente</a>
				</li>
				<li>
					<a class="page-link" asp-controller="Direcciones" asp-action="Index"
						asp-route-pg="@Model.TotalPages)">Último</a>
				</li>
			}
		</ul>
	}
</div>